### ISSUE TITLE
How to run the example?

### ISSUE THREAD

**Issue by zzzarius** [Bonitasoft-Community/page_foodtruck#1]
Hello,

I am new to BonitaBPM and I can't figure out how I should run the project. In BonitaBPM 7.2.1 IDE there's possibility to import file with .bos extension. Tried to rename .zip to .bos and open it in IDE with no luck. I tried to run project in groovy console and got following dependency problems:

_unable to resolve class org.bonitasoft.engine.identity.User
 at line: 31, column: 1
unable to resolve class org.bonitasoft.engine.exception.UnknownAPITypeException
 at line: 40, column: 1
unable to resolve class org.bonitasoft.console.common.server.page.PageResourceProvider
 at line: 34, column: 1
unable to resolve class org.bonitasoft.engine.command.CommandDescriptor
 at line: 61, column: 1
unable to resolve class org.bonitasoft.engine.bpm.flownode.ActivityInstanceSearchDescriptor
 at line: 53, column: 1
unable to resolve class com.bonitasoft.engine.api.PlatformMonitoringAPI
 at line: 50, column: 1
unable to resolve class com.bonitasoft.custompage.foodtruck.FoodTruckAccess
 at line: 69, column: 1
unable to resolve class org.bonitasoft.engine.search.SearchResult
 at line: 59, column: 1
unable to resolve class org.bonitasoft.engine.api.CommandAPI
 at line: 44, column: 1
unable to resolve class org.bonitasoft.engine.exception.DeletionException
 at line: 38, column: 1
unable to resolve class org.bonitasoft.engine.api.IdentityAPI
 at line: 47, column: 1
unable to resolve class com.bonitasoft.custompage.foodtruck.Toolbox.FoodTruckResult
 at line: 68, column: 1
unable to resolve class org.bonitasoft.engine.exception.BonitaHomeNotSetException
 at line: 36, column: 1
unable to resolve class org.bonitasoft.engine.bpm.flownode.ActivityInstance
 at line: 63, column: 1
unable to resolve class org.apache.commons.lang3.StringEscapeUtils
 at line: 29, column: 1
unable to resolve class org.json.simple.JSONValue
 at line: 16, column: 1
unable to resolve class org.bonitasoft.engine.api.ProfileAPI
 at line: 48, column: 1
unable to resolve class org.bonitasoft.engine.bpm.flownode.ArchivedActivityInstanceSearchDescriptor
 at line: 54, column: 1
unable to resolve class org.json.simple.JSONArray
 at line: 15, column: 1
unable to resolve class org.json.simple.JSONObject
 at line: 13, column: 1
unable to resolve class org.bonitasoft.engine.search.SearchOptions
 at line: 58, column: 1
unable to resolve class org.bonitasoft.console.common.server.page.PageController
 at line: 33, column: 1
unable to resolve class org.bonitasoft.engine.exception.ServerAPIException
 at line: 39, column: 1
unable to resolve class org.bonitasoft.engine.exception.CreationException
 at line: 37, column: 1
unable to resolve class org.bonitasoft.engine.command.CommandCriterion
 at line: 62, column: 1
unable to resolve class org.bonitasoft.engine.exception.AlreadyExistsException
 at line: 35, column: 1
unable to resolve class org.bonitasoft.console.common.server.page.PageContext
 at line: 32, column: 1
unable to resolve class org.bonitasoft.engine.api.PageAPI
 at line: 45, column: 1
unable to resolve class org.bonitasoft.engine.bpm.process.ProcessDeploymentInfo
 at line: 64, column: 1
unable to resolve class org.bonitasoft.engine.api.ProcessAPI
 at line: 46, column: 1
unable to resolve class org.bonitasoft.engine.bpm.flownode.ArchivedActivityInstance
 at line: 57, column: 1
unable to resolve class com.bonitasoft.custompage.foodtruck.FoodTruckAccess.FoodTruckParam
 at line: 67, column: 1
unable to resolve class com.bonitasoft.engine.api.TenantAPIAccessor
 at line: 42, column: 1
unable to resolve class org.bonitasoft.engine.session.APISession
 at line: 43, column: 1
unable to resolve class org.bonitasoft.engine.bpm.flownode.ArchivedFlowNodeInstance
 at line: 56, column: 1
unable to resolve class org.bonitasoft.engine.search.SearchOptionsBuilder
 at line: 51, column: 1_

**Comment by pierre-yves-monnet** [comment]
Hello
 the Fodtruck is a CustomPage. So to load it 
- access the Bonita Portal, log as Walter.Bates or start it from the IDE, click on Portal)
- select the profile Administrator
- go to the menu "Ressource" and then click on ADD
- give the ZIP file as a ressource
  The page is present !
  So, now you have to let this page vsible for a user.
- In menu Organisation, select "profile"
- click on ADD to add a new profile. Give a name (example : "custom").
- in the new profile, add the custom page AND register users (register for example Walter.Bates)
- logout / login as Walter Bates
- in the profile list, the profile "custom" should be visible.
- Access it, and then the page is visible

Somes informations here 
http://documentation.bonitasoft.com/custom-profiles-1#nav
