### ISSUE TITLE
Popup error in V7.4.3

### ISSUE THREAD

**Issue by Treiz13** [Bonitasoft-Community/page_foodtruck#3]
when we change page from Foodtruck to an other one we have this popup:

generate by this call:
http://localhost:8080/bonita/portal/custom-page/custompage_foodtruck/?page=custompage_foodtruck&action=listcustompage&json={%22showlocal%22:true,%22showBonitaAppsStore%22:true,%22github%22:{%22password%22:%22MyPASSWORD%22,%22login%22:%22mihaicoucy%22},%22gold%22:true,%22status%22:%22%22}

page:custompage_foodtruck
action:listcustompage
json:{"showlocal":true,"showBonitaAppsStore":true,"github":{"password":"MyPASSWORD","login":"mihaicoucy"},"gold":true,"status":""}

**Comment by pierre-yves-monnet** [comment]
The alert is removed
