### ISSUE TITLE
Server Error 500 by installing it in BPM 7.5.0

### ISSUE THREAD

**Issue by FunTomAS74** [Bonitasoft-Community/page_foodtruck#4]
I am new to Bonitasoft. I tried to install the zip file in Bonitasoft 7.5 by 
1.) Importing the foodtruck zip in Resources, then
2.) I created a new Application and pointed the Homepage to the index.html file.
Opening the custompage_foodtruck URL just throws a 500 Error.
Is it because i just got the Community Edition, where I cannot add Organization Profiles?
Regards

**Comment by pierre-yves-monnet** [comment]
You did well. 
The point is the custom page policy change, and are not ascendant compatible. So, an update must be done to run it after 7.3
In 7.5, a new change is made by Tomcat, and not compatible ascendant too : so this new feature are included too.

Try the foodtruck 1.1 and enjoy it !
Thanks for the reporting.
